---
root: true
ignorePatterns:
  - projects/**/*
env:
  browser: true
  node: false
  es6: true
overrides:
  - files:
      - "*.ts"
    plugins:
      - eslint-plugin-tsdoc
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@angular-eslint/recommended
      - plugin:@angular-eslint/template/process-inline-templates
    rules:
      "@angular-eslint/directive-selector":
        - error
        - type: attribute
          prefix: app
          style: camelCase
      "@angular-eslint/component-selector":
        - error
        - type: element
          prefix: app
          style: kebab-case
      no-var: warn
      camelcase: error
      eqeqeq: [error, always]
      capitalized-comments:
        - warn
        - always
        - ignoreConsecutiveComments: true
      curly: [error, multi-line, consistent]
  - files:
      - "*.html"
    extends:
      - plugin:@angular-eslint/template/recommended
      - plugin:@angular-eslint/template/accessibility
    rules: {}
