name: Build and deploy static content to Pages
run-name: ${{ github.actor }} deploys to Pages

on:
    push:
        branches: ['master']
        paths-ignore: ['**.md']
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
      name: Build static content
      runs-on: ubuntu-22.04
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Nodejs
          uses: actions/setup-node@v4.0.1
          with:
            node-version: "20.9"

        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        
        - name: Get/put yarn cache
          uses: actions/cache@v4.0.0
          with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

        - name: Install dependencies
          run: yarn install --prefer-offline 

#        - name: Test
#          run: yarn run test
 
        - name: Build
          run: yarn run build-gh-pages

        - name: Update pages artifacts
          uses: actions/upload-pages-artifact@v3.0.1
          with:
            path: dist/
    
    deploy:
      name: Deploy to GitHub Pages
      needs: build
      runs-on: ubuntu-22.04
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy static content
          id: deployment
          uses: actions/deploy-pages@v4.0.3
